[package]
name = "pkg_with_targets"
version = "0.1.0"

[target.thumbv7em-none-eabihf]
features = ["no_std", "cortex-m"]
opt_level = "s"
stack_size = 8192

[target.x86_64-unknown-linux]
features = ["std", "networking"]
opt_level = "3"
